### ISSUE TITLE
Botão para registrar a retirada da encomenda

### ISSUE THREAD

**Issue by wwgoncalves** [rocketseat-education/bootcamp-gostack-desafio-10#1]
Pessoal, não ficou faltando no layout, a partir da tela de detalhe da encomenda, um botão para a ação de "retirada" da encomenda? (Acredito que a data/hora de retirada registrada será a atual e nenhuma outra tela será necessária, correto?)
Obrigado!

**Comment by wwgoncalves** [comment]
@csorlandi e @josepholiveira, buenas! Contatei o João por e-mail que disse que falaria com vocês. O enunciado final e prazo do desafio foram enviados hoje. Chegaram a dar uma olhada nesta issue?

**Comment by josepholiveira** [comment]
Faala @wwgoncalves!

Acabei não vendo sua issue, mas se você perceber no layout, temos um grupo de botões “flutuante” que exibe as principais ações de uma encomenda do status como já retirada.

A exibição de uma encomenda PENDENTE vai ser nessa mesma tela, mas ao invés de termos os 3 botões, teremos um único botão para “retirar entrega”.  

Uma funcionalidade legal que vi um aluno implementando era de “segurar por 3 segundos” para que a entrega seja retirada, mas isso fica a seu critério 🚀
